// Auto-generated by scripts/generateAssetsManifest.js
import { Asset, Collection } from '../types';

export const localAssets: Asset[] = [
    {
        "id": "local-ICONS-CONSULTING-1",
        "name": "1",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.985Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/CONSULTING/1.png",
        "downloadUrl": "/assets/ICONS/CONSULTING/1.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "CONSULTING"
        ],
        "localPaths": {
            "png": "/assets/ICONS/CONSULTING/1.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-CONSULTING-10",
        "name": "10",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.985Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/CONSULTING/10.png",
        "downloadUrl": "/assets/ICONS/CONSULTING/10.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "CONSULTING"
        ],
        "localPaths": {
            "png": "/assets/ICONS/CONSULTING/10.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-CONSULTING-11",
        "name": "11",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.985Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/CONSULTING/11.png",
        "downloadUrl": "/assets/ICONS/CONSULTING/11.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "CONSULTING"
        ],
        "localPaths": {
            "png": "/assets/ICONS/CONSULTING/11.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-CONSULTING-12",
        "name": "12",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.985Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/CONSULTING/12.png",
        "downloadUrl": "/assets/ICONS/CONSULTING/12.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "CONSULTING"
        ],
        "localPaths": {
            "png": "/assets/ICONS/CONSULTING/12.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-CONSULTING-13",
        "name": "13",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.985Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/CONSULTING/13.png",
        "downloadUrl": "/assets/ICONS/CONSULTING/13.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "CONSULTING"
        ],
        "localPaths": {
            "png": "/assets/ICONS/CONSULTING/13.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-CONSULTING-14",
        "name": "14",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.985Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/CONSULTING/14.png",
        "downloadUrl": "/assets/ICONS/CONSULTING/14.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "CONSULTING"
        ],
        "localPaths": {
            "png": "/assets/ICONS/CONSULTING/14.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-CONSULTING-15",
        "name": "15",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.985Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/CONSULTING/15.png",
        "downloadUrl": "/assets/ICONS/CONSULTING/15.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "CONSULTING"
        ],
        "localPaths": {
            "png": "/assets/ICONS/CONSULTING/15.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-CONSULTING-16",
        "name": "16",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.985Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/CONSULTING/16.png",
        "downloadUrl": "/assets/ICONS/CONSULTING/16.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "CONSULTING"
        ],
        "localPaths": {
            "png": "/assets/ICONS/CONSULTING/16.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-CONSULTING-17",
        "name": "17",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.985Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/CONSULTING/17.png",
        "downloadUrl": "/assets/ICONS/CONSULTING/17.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "CONSULTING"
        ],
        "localPaths": {
            "png": "/assets/ICONS/CONSULTING/17.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-CONSULTING-18",
        "name": "18",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.985Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/CONSULTING/18.png",
        "downloadUrl": "/assets/ICONS/CONSULTING/18.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "CONSULTING"
        ],
        "localPaths": {
            "png": "/assets/ICONS/CONSULTING/18.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-CONSULTING-19",
        "name": "19",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.985Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/CONSULTING/19.png",
        "downloadUrl": "/assets/ICONS/CONSULTING/19.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "CONSULTING"
        ],
        "localPaths": {
            "png": "/assets/ICONS/CONSULTING/19.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-CONSULTING-2",
        "name": "2",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.985Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/CONSULTING/2.png",
        "downloadUrl": "/assets/ICONS/CONSULTING/2.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "CONSULTING"
        ],
        "localPaths": {
            "png": "/assets/ICONS/CONSULTING/2.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-CONSULTING-3",
        "name": "3",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.985Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/CONSULTING/3.png",
        "downloadUrl": "/assets/ICONS/CONSULTING/3.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "CONSULTING"
        ],
        "localPaths": {
            "png": "/assets/ICONS/CONSULTING/3.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-CONSULTING-4",
        "name": "4",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.985Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/CONSULTING/4.png",
        "downloadUrl": "/assets/ICONS/CONSULTING/4.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "CONSULTING"
        ],
        "localPaths": {
            "png": "/assets/ICONS/CONSULTING/4.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-CONSULTING-5",
        "name": "5",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.985Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/CONSULTING/5.png",
        "downloadUrl": "/assets/ICONS/CONSULTING/5.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "CONSULTING"
        ],
        "localPaths": {
            "png": "/assets/ICONS/CONSULTING/5.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-CONSULTING-6",
        "name": "6",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.985Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/CONSULTING/6.png",
        "downloadUrl": "/assets/ICONS/CONSULTING/6.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "CONSULTING"
        ],
        "localPaths": {
            "png": "/assets/ICONS/CONSULTING/6.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-CONSULTING-7",
        "name": "7",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.985Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/CONSULTING/7.png",
        "downloadUrl": "/assets/ICONS/CONSULTING/7.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "CONSULTING"
        ],
        "localPaths": {
            "png": "/assets/ICONS/CONSULTING/7.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-CONSULTING-8",
        "name": "8",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.985Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/CONSULTING/8.png",
        "downloadUrl": "/assets/ICONS/CONSULTING/8.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "CONSULTING"
        ],
        "localPaths": {
            "png": "/assets/ICONS/CONSULTING/8.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-CONSULTING-9",
        "name": "9",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.985Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/CONSULTING/9.png",
        "downloadUrl": "/assets/ICONS/CONSULTING/9.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "CONSULTING"
        ],
        "localPaths": {
            "png": "/assets/ICONS/CONSULTING/9.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-EXPERT-1",
        "name": "1",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/EXPERT/1.png",
        "downloadUrl": "/assets/ICONS/EXPERT/1.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "EXPERT"
        ],
        "localPaths": {
            "png": "/assets/ICONS/EXPERT/1.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-EXPERT-10",
        "name": "10",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/EXPERT/10.png",
        "downloadUrl": "/assets/ICONS/EXPERT/10.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "EXPERT"
        ],
        "localPaths": {
            "png": "/assets/ICONS/EXPERT/10.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-EXPERT-11",
        "name": "11",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/EXPERT/11.png",
        "downloadUrl": "/assets/ICONS/EXPERT/11.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "EXPERT"
        ],
        "localPaths": {
            "png": "/assets/ICONS/EXPERT/11.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-EXPERT-12",
        "name": "12",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/EXPERT/12.png",
        "downloadUrl": "/assets/ICONS/EXPERT/12.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "EXPERT"
        ],
        "localPaths": {
            "png": "/assets/ICONS/EXPERT/12.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-EXPERT-13",
        "name": "13",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/EXPERT/13.png",
        "downloadUrl": "/assets/ICONS/EXPERT/13.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "EXPERT"
        ],
        "localPaths": {
            "png": "/assets/ICONS/EXPERT/13.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-EXPERT-14",
        "name": "14",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/EXPERT/14.png",
        "downloadUrl": "/assets/ICONS/EXPERT/14.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "EXPERT"
        ],
        "localPaths": {
            "png": "/assets/ICONS/EXPERT/14.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-EXPERT-2",
        "name": "2",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/EXPERT/2.png",
        "downloadUrl": "/assets/ICONS/EXPERT/2.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "EXPERT"
        ],
        "localPaths": {
            "png": "/assets/ICONS/EXPERT/2.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-EXPERT-3",
        "name": "3",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/EXPERT/3.png",
        "downloadUrl": "/assets/ICONS/EXPERT/3.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "EXPERT"
        ],
        "localPaths": {
            "png": "/assets/ICONS/EXPERT/3.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-EXPERT-4",
        "name": "4",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/EXPERT/4.png",
        "downloadUrl": "/assets/ICONS/EXPERT/4.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "EXPERT"
        ],
        "localPaths": {
            "png": "/assets/ICONS/EXPERT/4.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-EXPERT-5",
        "name": "5",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/EXPERT/5.png",
        "downloadUrl": "/assets/ICONS/EXPERT/5.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "EXPERT"
        ],
        "localPaths": {
            "png": "/assets/ICONS/EXPERT/5.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-EXPERT-6",
        "name": "6",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/EXPERT/6.png",
        "downloadUrl": "/assets/ICONS/EXPERT/6.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "EXPERT"
        ],
        "localPaths": {
            "png": "/assets/ICONS/EXPERT/6.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-EXPERT-7",
        "name": "7",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/EXPERT/7.png",
        "downloadUrl": "/assets/ICONS/EXPERT/7.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "EXPERT"
        ],
        "localPaths": {
            "png": "/assets/ICONS/EXPERT/7.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-EXPERT-8",
        "name": "8",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/EXPERT/8.png",
        "downloadUrl": "/assets/ICONS/EXPERT/8.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "EXPERT"
        ],
        "localPaths": {
            "png": "/assets/ICONS/EXPERT/8.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-EXPERT-9",
        "name": "9",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/EXPERT/9.png",
        "downloadUrl": "/assets/ICONS/EXPERT/9.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "EXPERT"
        ],
        "localPaths": {
            "png": "/assets/ICONS/EXPERT/9.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-GROWTH-1",
        "name": "1",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/GROWTH/1.png",
        "downloadUrl": "/assets/ICONS/GROWTH/1.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "GROWTH"
        ],
        "localPaths": {
            "png": "/assets/ICONS/GROWTH/1.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-GROWTH-10",
        "name": "10",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/GROWTH/10.png",
        "downloadUrl": "/assets/ICONS/GROWTH/10.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "GROWTH"
        ],
        "localPaths": {
            "png": "/assets/ICONS/GROWTH/10.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-GROWTH-11",
        "name": "11",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/GROWTH/11.png",
        "downloadUrl": "/assets/ICONS/GROWTH/11.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "GROWTH"
        ],
        "localPaths": {
            "png": "/assets/ICONS/GROWTH/11.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-GROWTH-12",
        "name": "12",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/GROWTH/12.png",
        "downloadUrl": "/assets/ICONS/GROWTH/12.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "GROWTH"
        ],
        "localPaths": {
            "png": "/assets/ICONS/GROWTH/12.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-GROWTH-13",
        "name": "13",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/GROWTH/13.png",
        "downloadUrl": "/assets/ICONS/GROWTH/13.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "GROWTH"
        ],
        "localPaths": {
            "png": "/assets/ICONS/GROWTH/13.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-GROWTH-14",
        "name": "14",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/GROWTH/14.png",
        "downloadUrl": "/assets/ICONS/GROWTH/14.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "GROWTH"
        ],
        "localPaths": {
            "png": "/assets/ICONS/GROWTH/14.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-GROWTH-15",
        "name": "15",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/GROWTH/15.png",
        "downloadUrl": "/assets/ICONS/GROWTH/15.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "GROWTH"
        ],
        "localPaths": {
            "png": "/assets/ICONS/GROWTH/15.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-GROWTH-16",
        "name": "16",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/GROWTH/16.png",
        "downloadUrl": "/assets/ICONS/GROWTH/16.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "GROWTH"
        ],
        "localPaths": {
            "png": "/assets/ICONS/GROWTH/16.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-GROWTH-17",
        "name": "17",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/GROWTH/17.png",
        "downloadUrl": "/assets/ICONS/GROWTH/17.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "GROWTH"
        ],
        "localPaths": {
            "png": "/assets/ICONS/GROWTH/17.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-GROWTH-18",
        "name": "18",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/GROWTH/18.png",
        "downloadUrl": "/assets/ICONS/GROWTH/18.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "GROWTH"
        ],
        "localPaths": {
            "png": "/assets/ICONS/GROWTH/18.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-GROWTH-19",
        "name": "19",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/GROWTH/19.png",
        "downloadUrl": "/assets/ICONS/GROWTH/19.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "GROWTH"
        ],
        "localPaths": {
            "png": "/assets/ICONS/GROWTH/19.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-GROWTH-2",
        "name": "2",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/GROWTH/2.png",
        "downloadUrl": "/assets/ICONS/GROWTH/2.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "GROWTH"
        ],
        "localPaths": {
            "png": "/assets/ICONS/GROWTH/2.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-GROWTH-20",
        "name": "20",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/GROWTH/20.png",
        "downloadUrl": "/assets/ICONS/GROWTH/20.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "GROWTH"
        ],
        "localPaths": {
            "png": "/assets/ICONS/GROWTH/20.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-GROWTH-21",
        "name": "21",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/GROWTH/21.png",
        "downloadUrl": "/assets/ICONS/GROWTH/21.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "GROWTH"
        ],
        "localPaths": {
            "png": "/assets/ICONS/GROWTH/21.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-GROWTH-22",
        "name": "22",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/GROWTH/22.png",
        "downloadUrl": "/assets/ICONS/GROWTH/22.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "GROWTH"
        ],
        "localPaths": {
            "png": "/assets/ICONS/GROWTH/22.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-GROWTH-3",
        "name": "3",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/GROWTH/3.png",
        "downloadUrl": "/assets/ICONS/GROWTH/3.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "GROWTH"
        ],
        "localPaths": {
            "png": "/assets/ICONS/GROWTH/3.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-GROWTH-4",
        "name": "4",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/GROWTH/4.png",
        "downloadUrl": "/assets/ICONS/GROWTH/4.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "GROWTH"
        ],
        "localPaths": {
            "png": "/assets/ICONS/GROWTH/4.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-GROWTH-5",
        "name": "5",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/GROWTH/5.png",
        "downloadUrl": "/assets/ICONS/GROWTH/5.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "GROWTH"
        ],
        "localPaths": {
            "png": "/assets/ICONS/GROWTH/5.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-GROWTH-6",
        "name": "6",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/GROWTH/6.png",
        "downloadUrl": "/assets/ICONS/GROWTH/6.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "GROWTH"
        ],
        "localPaths": {
            "png": "/assets/ICONS/GROWTH/6.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-GROWTH-7",
        "name": "7",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/GROWTH/7.png",
        "downloadUrl": "/assets/ICONS/GROWTH/7.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "GROWTH"
        ],
        "localPaths": {
            "png": "/assets/ICONS/GROWTH/7.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-GROWTH-8",
        "name": "8",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/GROWTH/8.png",
        "downloadUrl": "/assets/ICONS/GROWTH/8.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "GROWTH"
        ],
        "localPaths": {
            "png": "/assets/ICONS/GROWTH/8.png",
            "svg": null
        }
    },
    {
        "id": "local-ICONS-GROWTH-9",
        "name": "9",
        "type": "Image",
        "format": "PNG",
        "availableFormats": [
            "PNG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/ICONS/GROWTH/9.png",
        "downloadUrl": "/assets/ICONS/GROWTH/9.png",
        "cloudUrl": null,
        "source": "local",
        "category": "ICONS",
        "tags": [
            "ICONS",
            "GROWTH"
        ],
        "localPaths": {
            "png": "/assets/ICONS/GROWTH/9.png",
            "svg": null
        }
    },
    {
        "id": "local-LOGO-root-LOGO_MOTION_SHIFT",
        "name": "LOGO MOTION SHIFT",
        "type": "video",
        "format": "MP4",
        "availableFormats": [
            "MP4"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/LOGO/LOGO_MOTION_SHIFT.mp4",
        "downloadUrl": "/assets/LOGO/LOGO_MOTION_SHIFT.mp4",
        "cloudUrl": null,
        "source": "local",
        "category": "LOGO",
        "tags": [
            "LOGO",
            "General"
        ],
        "localPaths": {
            "png": null,
            "svg": null
        }
    },
    {
        "id": "local-LOGO-1_TINTA-logo-FULL_3",
        "name": "logo FULL",
        "type": "Image",
        "format": "SVG",
        "availableFormats": [
            "PNG",
            "SVG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/LOGO/1_TINTA/THUMBNAILS/PNG/logo-FULL_3.png",
        "downloadUrl": "/assets/LOGO/1_TINTA/SVG/logo-FULL.svg",
        "cloudUrl": null,
        "source": "local",
        "category": "LOGO",
        "tags": [
            "LOGO",
            "1_TINTA"
        ],
        "localPaths": {
            "png": "/assets/LOGO/1_TINTA/PNG/logo-FULL.png",
            "svg": "/assets/LOGO/1_TINTA/SVG/logo-FULL.svg"
        }
    },
    {
        "id": "local-LOGO-1_TINTA-logo-compact_1",
        "name": "logo compact",
        "type": "Image",
        "format": "SVG",
        "availableFormats": [
            "PNG",
            "SVG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/LOGO/1_TINTA/THUMBNAILS/PNG/logo-compact_1.png",
        "downloadUrl": "/assets/LOGO/1_TINTA/SVG/logo-compact.svg",
        "cloudUrl": null,
        "source": "local",
        "category": "LOGO",
        "tags": [
            "LOGO",
            "1_TINTA"
        ],
        "localPaths": {
            "png": "/assets/LOGO/1_TINTA/PNG/logo-compact.png",
            "svg": "/assets/LOGO/1_TINTA/SVG/logo-compact.svg"
        }
    },
    {
        "id": "local-LOGO-1_TINTA-logo-mark_1",
        "name": "logo mark",
        "type": "Image",
        "format": "SVG",
        "availableFormats": [
            "PNG",
            "SVG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/LOGO/1_TINTA/THUMBNAILS/PNG/logo-mark_1.png",
        "downloadUrl": "/assets/LOGO/1_TINTA/SVG/logo-mark.svg",
        "cloudUrl": null,
        "source": "local",
        "category": "LOGO",
        "tags": [
            "LOGO",
            "1_TINTA"
        ],
        "localPaths": {
            "png": "/assets/LOGO/1_TINTA/PNG/logo-mark.png",
            "svg": "/assets/LOGO/1_TINTA/SVG/logo-mark.svg"
        }
    },
    {
        "id": "local-LOGO-1_TINTA-logo-reduced_3",
        "name": "logo reduced",
        "type": "Image",
        "format": "SVG",
        "availableFormats": [
            "PNG",
            "SVG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/LOGO/1_TINTA/THUMBNAILS/PNG/logo-reduced_3.png",
        "downloadUrl": "/assets/LOGO/1_TINTA/SVG/logo-reduced.svg",
        "cloudUrl": null,
        "source": "local",
        "category": "LOGO",
        "tags": [
            "LOGO",
            "1_TINTA"
        ],
        "localPaths": {
            "png": "/assets/LOGO/1_TINTA/PNG/logo-reduced.png",
            "svg": "/assets/LOGO/1_TINTA/SVG/logo-reduced.svg"
        }
    },
    {
        "id": "local-LOGO-2_TINTAS-logo-FULL_3",
        "name": "logo FULL",
        "type": "Image",
        "format": "SVG",
        "availableFormats": [
            "PNG",
            "SVG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/LOGO/2_TINTAS/THUMBNAILS/PNG/logo-FULL_3.png",
        "downloadUrl": "/assets/LOGO/2_TINTAS/SVG/logo-FULL.svg",
        "cloudUrl": null,
        "source": "local",
        "category": "LOGO",
        "tags": [
            "LOGO",
            "2_TINTAS"
        ],
        "localPaths": {
            "png": "/assets/LOGO/2_TINTAS/PNG/logo-FULL.png",
            "svg": "/assets/LOGO/2_TINTAS/SVG/logo-FULL.svg"
        }
    },
    {
        "id": "local-LOGO-2_TINTAS-logo-compact_1",
        "name": "logo compact",
        "type": "Image",
        "format": "SVG",
        "availableFormats": [
            "PNG",
            "SVG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/LOGO/2_TINTAS/THUMBNAILS/PNG/logo-compact_1.png",
        "downloadUrl": "/assets/LOGO/2_TINTAS/SVG/logo-compact.svg",
        "cloudUrl": null,
        "source": "local",
        "category": "LOGO",
        "tags": [
            "LOGO",
            "2_TINTAS"
        ],
        "localPaths": {
            "png": "/assets/LOGO/2_TINTAS/PNG/logo-compact.png",
            "svg": "/assets/LOGO/2_TINTAS/SVG/logo-compact.svg"
        }
    },
    {
        "id": "local-LOGO-2_TINTAS-logo-mark_1",
        "name": "logo mark",
        "type": "Image",
        "format": "SVG",
        "availableFormats": [
            "PNG",
            "SVG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/LOGO/2_TINTAS/THUMBNAILS/PNG/logo-mark_1.png",
        "downloadUrl": "/assets/LOGO/2_TINTAS/SVG/logo-mark.svg",
        "cloudUrl": null,
        "source": "local",
        "category": "LOGO",
        "tags": [
            "LOGO",
            "2_TINTAS"
        ],
        "localPaths": {
            "png": "/assets/LOGO/2_TINTAS/PNG/logo-mark.png",
            "svg": "/assets/LOGO/2_TINTAS/SVG/logo-mark.svg"
        }
    },
    {
        "id": "local-LOGO-2_TINTAS-logo-reduced_3",
        "name": "logo reduced",
        "type": "Image",
        "format": "SVG",
        "availableFormats": [
            "PNG",
            "SVG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/LOGO/2_TINTAS/THUMBNAILS/PNG/logo-reduced_3.png",
        "downloadUrl": "/assets/LOGO/2_TINTAS/SVG/logo-reduced.svg",
        "cloudUrl": null,
        "source": "local",
        "category": "LOGO",
        "tags": [
            "LOGO",
            "2_TINTAS"
        ],
        "localPaths": {
            "png": "/assets/LOGO/2_TINTAS/PNG/logo-reduced.png",
            "svg": "/assets/LOGO/2_TINTAS/SVG/logo-reduced.svg"
        }
    },
    {
        "id": "local-LOGO-FULL_COLOR-logo-FULL_2",
        "name": "logo FULL",
        "type": "Image",
        "format": "SVG",
        "availableFormats": [
            "PNG",
            "SVG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/LOGO/FULL_COLOR/THUMBNAILS/PNG/logo-FULL_2.png",
        "downloadUrl": "/assets/LOGO/FULL_COLOR/SVG/logo-FULL_1.svg",
        "cloudUrl": null,
        "source": "local",
        "category": "LOGO",
        "tags": [
            "LOGO",
            "FULL_COLOR"
        ],
        "localPaths": {
            "png": "/assets/LOGO/FULL_COLOR/PNG/logo-FULL_1.png",
            "svg": "/assets/LOGO/FULL_COLOR/SVG/logo-FULL_1.svg"
        }
    },
    {
        "id": "local-LOGO-FULL_COLOR-logo-reduced_2",
        "name": "logo reduced",
        "type": "Image",
        "format": "SVG",
        "availableFormats": [
            "PNG",
            "SVG"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.986Z",
        "owner": "Local",
        "previewUrl": "/assets/LOGO/FULL_COLOR/THUMBNAILS/PNG/logo-reduced_2.png",
        "downloadUrl": "/assets/LOGO/FULL_COLOR/SVG/logo-reduced_1.svg",
        "cloudUrl": null,
        "source": "local",
        "category": "LOGO",
        "tags": [
            "LOGO",
            "FULL_COLOR"
        ],
        "localPaths": {
            "png": "/assets/LOGO/FULL_COLOR/PNG/logo-reduced_1.png",
            "svg": "/assets/LOGO/FULL_COLOR/SVG/logo-reduced_1.svg"
        }
    },
    {
        "id": "local-MOTION-root-ESPIRAL_SHIFT_PN",
        "name": "ESPIRAL SHIFT PN",
        "type": "video",
        "format": "MP4",
        "availableFormats": [
            "MP4"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.987Z",
        "owner": "Local",
        "previewUrl": "/assets/MOTION/ESPIRAL_SHIFT_PN.mp4",
        "downloadUrl": "/assets/MOTION/ESPIRAL_SHIFT_PN.mp4",
        "cloudUrl": null,
        "source": "local",
        "category": "MOTION",
        "tags": [
            "MOTION",
            "General"
        ],
        "localPaths": {
            "png": null,
            "svg": null
        }
    },
    {
        "id": "local-MOTION-root-LOGO_MOTION_SHIFT",
        "name": "LOGO MOTION SHIFT",
        "type": "video",
        "format": "MP4",
        "availableFormats": [
            "MP4"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.987Z",
        "owner": "Local",
        "previewUrl": "/assets/MOTION/LOGO_MOTION_SHIFT.mp4",
        "downloadUrl": "/assets/MOTION/LOGO_MOTION_SHIFT.mp4",
        "cloudUrl": null,
        "source": "local",
        "category": "MOTION",
        "tags": [
            "MOTION",
            "General"
        ],
        "localPaths": {
            "png": null,
            "svg": null
        }
    },
    {
        "id": "local-MOTION-root-RESONANCIAmp4",
        "name": "RESONANCIAmp4",
        "type": "video",
        "format": "MP4",
        "availableFormats": [
            "MP4"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.987Z",
        "owner": "Local",
        "previewUrl": "/assets/MOTION/RESONANCIAmp4.mp4",
        "downloadUrl": "/assets/MOTION/RESONANCIAmp4.mp4",
        "cloudUrl": null,
        "source": "local",
        "category": "MOTION",
        "tags": [
            "MOTION",
            "General"
        ],
        "localPaths": {
            "png": null,
            "svg": null
        }
    },
    {
        "id": "local-MOTION-root-TWIST_SHIFT_PN",
        "name": "TWIST SHIFT PN",
        "type": "video",
        "format": "MP4",
        "availableFormats": [
            "MP4"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.987Z",
        "owner": "Local",
        "previewUrl": "/assets/MOTION/TWIST_SHIFT_PN.mp4",
        "downloadUrl": "/assets/MOTION/TWIST_SHIFT_PN.mp4",
        "cloudUrl": null,
        "source": "local",
        "category": "MOTION",
        "tags": [
            "MOTION",
            "General"
        ],
        "localPaths": {
            "png": null,
            "svg": null
        }
    },
    {
        "id": "local-MOTION-root-WAVES_SHIFT_PN",
        "name": "WAVES SHIFT PN",
        "type": "video",
        "format": "MP4",
        "availableFormats": [
            "MP4"
        ],
        "size": "N/A",
        "modified": "2026-02-19T20:19:05.987Z",
        "owner": "Local",
        "previewUrl": "/assets/MOTION/WAVES_SHIFT_PN.mp4",
        "downloadUrl": "/assets/MOTION/WAVES_SHIFT_PN.mp4",
        "cloudUrl": null,
        "source": "local",
        "category": "MOTION",
        "tags": [
            "MOTION",
            "General"
        ],
        "localPaths": {
            "png": null,
            "svg": null
        }
    }
];

export const localCollections: Collection[] = [
    {
        "id": "ICONS",
        "title": "ICONS",
        "coverVideoUrl": "/assets/ICONS/ICONSTHUMBNAIL.mp4",
        "coverImageUrl": null,
        "itemCount": 55,
        "route": "/assets/icons"
    },
    {
        "id": "LOGO",
        "title": "System Logos",
        "coverVideoUrl": "/assets/LOGO/LOGO_MOTION_SHIFT.mp4",
        "coverImageUrl": null,
        "itemCount": 11,
        "route": "/assets/logo"
    },
    {
        "id": "MOTION",
        "title": "MOTION",
        "coverVideoUrl": "/assets/MOTION/WAVES_SHIFT_PN.mp4",
        "coverImageUrl": null,
        "itemCount": 5,
        "route": "/assets/motion"
    }
];
